### ISSUE TITLE
Inconsistent Docstring Styles and Python Style Guide

### ISSUE THREAD

**Issue by MarcoR1791** [SPARQL-Anything/PySPARQL-Anything#12]
The style that I use to write docstrings has changed over time, so that there are multiple styles at once throughout the code at present.

Ideally, the code documentation should be rendered  stylistically homogeneous. 

On this note, it might be worth settling on a style for the project moving forward, both for the docstrings and the Python code developed.

The official Python documents are [1](https://peps.python.org/pep-0257/) and [2](https://peps.python.org/pep-0008/) for docstrings and code respectively.

Lately though I have actually been using the Google Python style guide [3](https://google.github.io/styleguide/pyguide.html#s3-python-style-rules), which covers pretty much everything. The only thing I disagree with it is over the linting tool to be used. I find ```pylint``` needlessly opinionated in some things and would be inclined more towards ```flake8``` instead.

@enridaga opinions are welcome!

**Comment by enridaga** [comment]
I don't have experience of that, maybe others have.
