### ISSUE TITLE
Update Management

### ISSUE THREAD

**Issue by MarcoR1791** [SPARQL-Anything/PySPARQL-Anything#15]
As the plan moving forward is to release a new version of PySPARQL Anything for each new SPARQL Anything release, how should we interact with the user with respect to this @enridaga ?

1) Should we notify the user automatically that a new version is available and then let them proceed manually to the update process, or

2) Should we notify the user and possibly give them an option (Y/N) to proceed with the update process automatically?

**Comment by enridaga** [comment]
I am not sure how option 2 can work, also, do you mean checking for a new release on every execution? Not a great idea for performance etc...

How other python libs deal with notifying updates?

**Comment by enridaga** [comment]
I am not sure how option 2 can work, also, do you mean checking for a new release on every execution? Not a great idea for performance etc...

How other python libs deal with notifying updates?

**Comment by MarcoR1791** [comment]
After looking at how other python apps do this, or don't do this, there is no need to implement this.
