### ISSUE TITLE
dependencies should be setup more flexible

### ISSUE THREAD

**Issue by seebi** [SPARQL-Anything/PySPARQL-Anything#18]
I suggest to specify the dependencies here

https://github.com/SPARQL-Anything/PySPARQL-Anything/blob/main/pyproject.toml#L34

more relaxed, in order to use your library more easy in other projects.

See also -> caret notification: https://python-poetry.org/docs/dependency-specification/#caret-requirements

**Comment by MarcoR1791** [comment]
Hi Sebastian,

Thank you for your suggestion! We had encountered the same problem while preparing a Colab demo for PySPARQL.

When it comes to determining the range of the dependency to specify, do you have any specific methods in mind?
Or must it be a trial and error process?

**Comment by seebi** [comment]
Most of the python packages adhere to semantic versioning so it should be save to use `^X` where `X` is the latest major version.

**Comment by seebi** [comment]
Maybe lets discuss this on the demo and poster session :-)
