### ISSUE TITLE
RDFLib integration

### ISSUE THREAD

**Issue by mielvds** [SPARQL-Anything/PySPARQL-Anything#4]
It would be useful if you could directly get an RDFlib `Graph` object from it. We've been using SA in that way, so we have some code lying around that we could contribute.

**Comment by MarcoR1791** [comment]
Hi Miel,

Might the following method (in class ```pysparql_anything.sparql_anything.SparqlAnything ```) be what you are looking for?
```
construct(**kwargs)
"""Executes a CONSTRUCT query and returns a rdflib graph object."""
```

**Comment by mielvds** [comment]
Ow I missed that. Perfect, thanks!
